version: "3.7"
services:
  frontend:
    container_name: lawpath_frontend
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - "./web:/var/app/web"
      - "/var/app/web/node_modules"
    stdin_open: true

  backend:
    container_name: lawpath_backend
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 8181:8080
    volumes:
      - "./api:/var/app/api"
      - "/var/app/api/node_modules"
    stdin_open: true
